/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ExerciseState, NextExerciseRequestedEvent, StateChangedEvent, } from "./components/shared/exercise-frame/exercise-frame";
export namespace Components {
    interface ExerciseBreadthFirstSearch {
    }
    interface ExerciseFrame {
        "state": ExerciseState;
    }
    interface ExerciseMinimumNumberOfEdgesOfConnectedGraph {
    }
    interface ExerciseModalValue {
    }
    interface ExerciseNumberPrompt {
        "expectedNumber": number;
    }
    interface ExercisePicker {
    }
    interface ExerciseTest {
    }
    interface ExerciseTextPrompt {
        "possibleAnswers": string[];
    }
}
declare global {
    interface HTMLExerciseBreadthFirstSearchElement extends Components.ExerciseBreadthFirstSearch, HTMLStencilElement {
    }
    var HTMLExerciseBreadthFirstSearchElement: {
        prototype: HTMLExerciseBreadthFirstSearchElement;
        new (): HTMLExerciseBreadthFirstSearchElement;
    };
    interface HTMLExerciseFrameElement extends Components.ExerciseFrame, HTMLStencilElement {
    }
    var HTMLExerciseFrameElement: {
        prototype: HTMLExerciseFrameElement;
        new (): HTMLExerciseFrameElement;
    };
    interface HTMLExerciseMinimumNumberOfEdgesOfConnectedGraphElement extends Components.ExerciseMinimumNumberOfEdgesOfConnectedGraph, HTMLStencilElement {
    }
    var HTMLExerciseMinimumNumberOfEdgesOfConnectedGraphElement: {
        prototype: HTMLExerciseMinimumNumberOfEdgesOfConnectedGraphElement;
        new (): HTMLExerciseMinimumNumberOfEdgesOfConnectedGraphElement;
    };
    interface HTMLExerciseModalValueElement extends Components.ExerciseModalValue, HTMLStencilElement {
    }
    var HTMLExerciseModalValueElement: {
        prototype: HTMLExerciseModalValueElement;
        new (): HTMLExerciseModalValueElement;
    };
    interface HTMLExerciseNumberPromptElement extends Components.ExerciseNumberPrompt, HTMLStencilElement {
    }
    var HTMLExerciseNumberPromptElement: {
        prototype: HTMLExerciseNumberPromptElement;
        new (): HTMLExerciseNumberPromptElement;
    };
    interface HTMLExercisePickerElement extends Components.ExercisePicker, HTMLStencilElement {
    }
    var HTMLExercisePickerElement: {
        prototype: HTMLExercisePickerElement;
        new (): HTMLExercisePickerElement;
    };
    interface HTMLExerciseTestElement extends Components.ExerciseTest, HTMLStencilElement {
    }
    var HTMLExerciseTestElement: {
        prototype: HTMLExerciseTestElement;
        new (): HTMLExerciseTestElement;
    };
    interface HTMLExerciseTextPromptElement extends Components.ExerciseTextPrompt, HTMLStencilElement {
    }
    var HTMLExerciseTextPromptElement: {
        prototype: HTMLExerciseTextPromptElement;
        new (): HTMLExerciseTextPromptElement;
    };
    interface HTMLElementTagNameMap {
        "exercise-breadth-first-search": HTMLExerciseBreadthFirstSearchElement;
        "exercise-frame": HTMLExerciseFrameElement;
        "exercise-minimum-number-of-edges-of-connected-graph": HTMLExerciseMinimumNumberOfEdgesOfConnectedGraphElement;
        "exercise-modal-value": HTMLExerciseModalValueElement;
        "exercise-number-prompt": HTMLExerciseNumberPromptElement;
        "exercise-picker": HTMLExercisePickerElement;
        "exercise-test": HTMLExerciseTestElement;
        "exercise-text-prompt": HTMLExerciseTextPromptElement;
    }
}
declare namespace LocalJSX {
    interface ExerciseBreadthFirstSearch {
    }
    interface ExerciseFrame {
        "onNextExerciseRequested"?: (event: CustomEvent<NextExerciseRequestedEvent>) => void;
        "onStateChanged"?: (event: CustomEvent<StateChangedEvent>) => void;
        "state"?: ExerciseState;
    }
    interface ExerciseMinimumNumberOfEdgesOfConnectedGraph {
    }
    interface ExerciseModalValue {
    }
    interface ExerciseNumberPrompt {
        "expectedNumber"?: number;
    }
    interface ExercisePicker {
    }
    interface ExerciseTest {
    }
    interface ExerciseTextPrompt {
        "possibleAnswers"?: string[];
    }
    interface IntrinsicElements {
        "exercise-breadth-first-search": ExerciseBreadthFirstSearch;
        "exercise-frame": ExerciseFrame;
        "exercise-minimum-number-of-edges-of-connected-graph": ExerciseMinimumNumberOfEdgesOfConnectedGraph;
        "exercise-modal-value": ExerciseModalValue;
        "exercise-number-prompt": ExerciseNumberPrompt;
        "exercise-picker": ExercisePicker;
        "exercise-test": ExerciseTest;
        "exercise-text-prompt": ExerciseTextPrompt;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "exercise-breadth-first-search": LocalJSX.ExerciseBreadthFirstSearch & JSXBase.HTMLAttributes<HTMLExerciseBreadthFirstSearchElement>;
            "exercise-frame": LocalJSX.ExerciseFrame & JSXBase.HTMLAttributes<HTMLExerciseFrameElement>;
            "exercise-minimum-number-of-edges-of-connected-graph": LocalJSX.ExerciseMinimumNumberOfEdgesOfConnectedGraph & JSXBase.HTMLAttributes<HTMLExerciseMinimumNumberOfEdgesOfConnectedGraphElement>;
            "exercise-modal-value": LocalJSX.ExerciseModalValue & JSXBase.HTMLAttributes<HTMLExerciseModalValueElement>;
            "exercise-number-prompt": LocalJSX.ExerciseNumberPrompt & JSXBase.HTMLAttributes<HTMLExerciseNumberPromptElement>;
            "exercise-picker": LocalJSX.ExercisePicker & JSXBase.HTMLAttributes<HTMLExercisePickerElement>;
            "exercise-test": LocalJSX.ExerciseTest & JSXBase.HTMLAttributes<HTMLExerciseTestElement>;
            "exercise-text-prompt": LocalJSX.ExerciseTextPrompt & JSXBase.HTMLAttributes<HTMLExerciseTextPromptElement>;
        }
    }
}
