/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import {HTMLStencilElement, JSXBase} from '@stencil/core/internal';
import {
  ExerciseState,
  NextExerciseRequestedEvent,
  StateChangedEvent,
} from './components/shared/exercise-frame/exercise-frame';

export namespace Components {
    interface ExerciseBreadthFirstSearch {
    }
    interface ExerciseFrame {
        "state": ExerciseState;
    }
    interface ExercisePicker {
    }
    interface ExerciseTest {
    }
}
declare global {
    interface HTMLExerciseBreadthFirstSearchElement extends Components.ExerciseBreadthFirstSearch, HTMLStencilElement {
    }
    var HTMLExerciseBreadthFirstSearchElement: {
        prototype: HTMLExerciseBreadthFirstSearchElement;
        new (): HTMLExerciseBreadthFirstSearchElement;
    };
    interface HTMLExerciseFrameElement extends Components.ExerciseFrame, HTMLStencilElement {
    }
    var HTMLExerciseFrameElement: {
        prototype: HTMLExerciseFrameElement;
        new (): HTMLExerciseFrameElement;
    };
    interface HTMLExercisePickerElement extends Components.ExercisePicker, HTMLStencilElement {
    }
    var HTMLExercisePickerElement: {
        prototype: HTMLExercisePickerElement;
        new (): HTMLExercisePickerElement;
    };
    interface HTMLExerciseTestElement extends Components.ExerciseTest, HTMLStencilElement {
    }
    var HTMLExerciseTestElement: {
        prototype: HTMLExerciseTestElement;
        new (): HTMLExerciseTestElement;
    };
    interface HTMLElementTagNameMap {
        "exercise-breadth-first-search": HTMLExerciseBreadthFirstSearchElement;
        "exercise-frame": HTMLExerciseFrameElement;
        "exercise-picker": HTMLExercisePickerElement;
        "exercise-test": HTMLExerciseTestElement;
    }
}
declare namespace LocalJSX {
    interface ExerciseBreadthFirstSearch {
    }
    interface ExerciseFrame {
        "onNextExerciseRequested"?: (event: CustomEvent<NextExerciseRequestedEvent>) => void;
        "onStateChanged"?: (event: CustomEvent<StateChangedEvent>) => void;
        "state"?: ExerciseState;
    }
    interface ExercisePicker {
    }
    interface ExerciseTest {
    }
    interface IntrinsicElements {
        "exercise-breadth-first-search": ExerciseBreadthFirstSearch;
        "exercise-frame": ExerciseFrame;
        "exercise-picker": ExercisePicker;
        "exercise-test": ExerciseTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "exercise-breadth-first-search": LocalJSX.ExerciseBreadthFirstSearch & JSXBase.HTMLAttributes<HTMLExerciseBreadthFirstSearchElement>;
            "exercise-frame": LocalJSX.ExerciseFrame & JSXBase.HTMLAttributes<HTMLExerciseFrameElement>;
            "exercise-picker": LocalJSX.ExercisePicker & JSXBase.HTMLAttributes<HTMLExercisePickerElement>;
            "exercise-test": LocalJSX.ExerciseTest & JSXBase.HTMLAttributes<HTMLExerciseTestElement>;
        }
    }
}
