/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ExerciseTest {
    }
}
declare global {
    interface HTMLExerciseTestElement extends Components.ExerciseTest, HTMLStencilElement {
    }
    var HTMLExerciseTestElement: {
        prototype: HTMLExerciseTestElement;
        new (): HTMLExerciseTestElement;
    };
    interface HTMLElementTagNameMap {
        "exercise-test": HTMLExerciseTestElement;
    }
}
declare namespace LocalJSX {
    interface ExerciseTest {
    }
    interface IntrinsicElements {
        "exercise-test": ExerciseTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "exercise-test": LocalJSX.ExerciseTest & JSXBase.HTMLAttributes<HTMLExerciseTestElement>;
        }
    }
}
